### ISSUE TITLE
docs not working

### ISSUE THREAD

**Issue by borma425** [AmineSoukara/EgyBest-API#6]
the docs site not working , you can put it in the same repo

**Comment by AmineSoukara** [comment]
> the docs site not working , you can put it in the same repo
![Screenshot_20220913-143611_Chrome](https://user-images.githubusercontent.com/65272894/189915759-1a714e6e-bca7-4a01-a0f4-97aa6c3f437f.jpg)

If You Are From Egypt.  The Site Is Banned There ... I'll Create New Docs Tonight 😁

**Comment by AmineSoukara** [comment]
> the docs site not working , you can put it in the same repo

[🆕️ Docs](https://github.com/AmineSoukara/EgyBest-API#-docs--examples)
